1810:
  本社: 東京都中央区新川1丁目17番22号
  東京支店: 東京都中央区新川1丁目17番22号
3865:
  本社他: 東京都中央区日本橋本石町3-2-2
4951:
  本社・首都圏支店: 東京都新宿区下落合1丁目4番10号
5189:
  本社他: 東京都渋谷区笹塚1丁目48番3号 笹塚太陽ビル5階
  笹塚ショッピングモール他: 東京都渋谷区笹塚1丁目21番17号
5388:
  本社: 東京都千代田区丸の内1丁目4番5号
  本社その他(推定): 東京都千代田区岩本町1丁目10番5号
6140:
  本社他: 東京都千代田区丸の内1丁目4番1号
9059:
  本社: 東京都千代田区丸の内1丁目1番2号
  浮間物流センター: 東京都北区浮間4丁目22番1号
9351:
  本社: 東京都中央区日本橋2丁目7番1号
9929:
  本社・東京本店: 東京都中央区新川1丁目22番11号
