"8841":
  TOCビル: 東京都品川区西五反田7-22-17
  第2TOCビル: 東京都品川区西五反田7-21-11
  第3TOCビル: 東京都品川区西五反田7-23-1
  第5TOCビル: 東京都品川区西五反田7-21-1
  TOC ANNEX: 東京都品川区西五反田7-9-4
  TOC両国ビル: 東京都墨田区両国2-10-5
  大崎ニューシティ: 東京都品川区大崎1-6-1
  TOC有明: 東京都江東区有明3-5-7
  TOC CONNECT: 東京都品川区西五反田7-22-17
